### ISSUE TITLE
Print Width is not respected

### ISSUE THREAD

**Issue by CyberMew** [azz/prettier-tslint#30] opened 2019-02-26 01:57 UTC
Prettier in VSCode settings is set to 80. Tslint Integration has been set. tslint.json has `"max-line-length": [true, 80]`

I tried creating a `.prettierrc.json` file with `"printWidth": 80` but it also doesn't work.

Is this a bug or am I missing something?

**Comment by aleclarson** [comment] 2019-02-26 02:03
Can you reproduce with `prettier-tslint` in command line?

What is happening instead?

**Comment by AhmedMKamal** [comment] 2019-03-03 00:35
Hi, @aleclarson I'm facing the same issue here, this is the rule in `tslint.json`
```
"max-line-length": [
            true,
            {
                "limit": 100,
                "ignore-pattern": "^import |^export {(.*?)}"
            }
        ]
```
using npm  `"pretty": "prettier-tslint fix **/*.ts"` the rule seems to be ignored and lines wrap at 80 columns, but for me adding `.prettierrc` file with `"printWidth": 100` fixed the issue.

@CyberMew please try to rename `.prettierrc.json` to `.prettierrc` and check if it's going to solve the problem.

**Comment by aleclarson** [comment] 2019-03-03 00:38
@AhmedMKamal That's not the same. You're looking for #25.

@CyberMew is claiming that neither Prettier's `printWidth` nor TSLint's `max-line-length` are being respected, even when they're equal.

**Comment by CyberMew** [comment] 2019-04-04 03:26
> Can you reproduce with `prettier-tslint` in command line?
> 
> What is happening instead?

Sorry for the late reply. Nothing happens to the file when I run the command, no output either. I wonder whose issue this belongs to. 

```
mac:react-native username$ npx prettier-tslint fix ./src/Components/SelectionRow.ts 
./src/Components/SelectionRow.ts
```

There are several situations where it will just flatout exceed 80 characters even when I have formatted it manually nicely. You can also reproduce this easily by having a long line like this:
```
import { SelectionRow as Template } from "Some/Very/Long/Name/That/Just/Exceeds80/SelectionRow";
```
I think by right it should format it to:
```
import {
  SelectionRow as Template
 } from "Some/Very/Long/Name/That/Just/Exceeds80/SelectionRow";
```

**Comment by aleclarson** [comment] 2019-04-04 13:08
Prettier leaves that `import` statement alone. See [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGU4AbOMGVaAJQgHd8BDAZ3wBU4szn58AvvgBmOCOnwAdEMXFwA9ADU4OAJ7yAMtADm8gHLN0CjgAs+8gFIBXVjHkBRAB5g4cACasAHAAZ5pClQ0UPQM0gDcklAgADQgEJjU0KzIoMw4YgwACmkIySjMAG4QqG4xIABGOMxgANZwMMSY1ahQ2sgwOFZwsSYw6GQA6iao8KxNLqRQrCOoBSOqyOCsybEtrCowmVXa6MzIwsxk67EAVqyOAEJVtfXEhnAaLXD7h8cgZ47ELdoUAIpWEHgLyO3RATRw6xwi3KzHKqjI0DKmBwLRgAxKMBMyB8sWREHWAyqmEWyLgkIKz1iODgAEcrKhqVtmDs9kgDiDYut0Kh2p1QdNWn8AUC2a9QTBYei3JjkAAmWIdZioMjfADC4l2iyg0EpIBscA4sLy7PWAgEQA).

Closing this until you provide a sample repository.

**Closed by aleclarson** 2019-04-04 13:08 UTC
